# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
         - 192.168.1.86/24
      gateway4: 192.168.1.1
      nameservers:
         addresses: [192.168.1.1, 8.8.8.8]
